import type { BrandRow, MarketingCampaignRow, MarketingPlatform, ContentFormat } from "../types";
import { buildBrandBlock } from "./shared";

export const VIDEO_SCRIPT_SYSTEM_PROMPT = `You are a short-form video scriptwriter. You write scripts a founder can film on a phone in one take, and scene plans an AI video generator can render. Hooks come first; every second earns the next.

Return a single JSON object with this exact shape:
{
  "hook": string,
  "script": string,
  "scenes": [
    { "visual": string, "voiceover": string, "duration_s": number }
  ],
  "video_prompt": string,
  "caption": string,
  "hashtags": string[]
}

Field guidance:
- "hook": the first 1-2 spoken lines. Must create an open loop or name a sharp pain within 3 seconds.
- "script": the full spoken script, conversational, 30-60 seconds when read aloud. Short sentences. Write it so a founder can read it naturally to camera — include (pause) and (smile) delivery notes sparingly.
- "scenes": 3-6 scenes covering the whole script. "visual" describes what is on screen; "voiceover" is the exact script portion; "duration_s" is seconds (total 30-60).
- "video_prompt": one paragraph describing the full video for an AI video generator (subject, setting, mood, camera movement). Used only when the video is AI-generated.
- "caption": the post caption to accompany the video (2-4 short lines, soft CTA).
- "hashtags": 3-8 lowercase hashtags without the # symbol.

Style:
- Match the brand voice exactly. No hype, no "wait for it".
- Never fabricate testimonials or statistics.

Return only the JSON object. No prose before or after.`;

export function buildVideoScriptPrompt(
  brand: BrandRow,
  campaign: MarketingCampaignRow | null,
  angle: string | null,
  platform: MarketingPlatform,
  format: ContentFormat,
  founderFilmed: boolean,
): string {
  const lines = [buildBrandBlock(brand)];
  lines.push(`Platform: ${platform}`);
  lines.push(`Format: ${format}`);
  lines.push(
    founderFilmed
      ? "This will be filmed by the founder talking to camera on a phone. Optimize the script for natural one-take delivery."
      : "This will be generated by an AI video model. Optimize the scenes and video_prompt for generation.",
  );
  if (campaign) {
    lines.push(`Campaign: ${campaign.name}`);
    if (campaign.objective) lines.push(`Objective: ${campaign.objective}`);
    if (campaign.brief) lines.push(`Brief: ${campaign.brief}`);
  }
  if (angle) lines.push(`Angle: ${angle}`);
  lines.push("Write one short-form video script.");
  return lines.join("\n\n");
}
